### ISSUE TITLE
demultiplex output is all put in undetermined

### ISSUE THREAD

**Issue by LisanneL** [compbiomed/scruff#93]
I have tried running the script to demultiplex single cell RNA-seq data from lane (1-4) to per cell, based on the example. The barcode file consists of a list of 384 8bp barcodes which I read into R as a vector.
> demultiplex(project = "UMC-LL-Q001", experiment = "UMC-LL-Q001", lane = "LL001", read1Path = "UMC-LL-001_L001-R1.fastq", read2Path = "UMC-LL-001_L001-R2.fastq", bc = "barcode", bcStart = 7, bcStop = 14, bcEdit = 0, umiStart = 1, umiStop = 6, keep = 75, minQual = 10, yieldReads = 1e+06, outDir = "./Demultiplex", summaryPrefix = "demultiplex", overwrite = FALSE, cores = max(1, parallel::detectCores() - 2), verbose = TRUE, logfilePrefix = format(Sys.time(), "%Y%m%d_%H%M%S"))

Whereas the example runs smoothly with my data I get the comment below in R while it's putting all fastq files in undetermined R1 and R2.fastq files, but there is no error message. Also in the log it just says processing x reads etc till it is completed.

Input sample information for FASTQ files: 
       project          experiment     lane    read1_path                           read2_path
1: UMC-LL-Q001 UMC-LL-Q001 LL001 UMC-LL-001_L001-R1.fastq UMC-LL-001_L001-R2.fastq

I have checked both R1 and R2 files for the barcodes and I can find them back. I hope you have some suggestion to help me, as I don't know what the problem is.

Thanks,
Lisanne

**Comment by zhewa** [comment]
Hi @LisanneL 

Thank you for posting a question about the scruff package. Can you try changing ``bc = "barcode"`` to the variable which is used to store the cell barcode character vector? You might want to remove the quotes (``"``) if it's stored in ``barcode``. Let me know if the problem persists.

Zhe
